services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api

    restart: always

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
